sudo: false
language: node_js
node_js:
- lts/*
cache:
- node_modules
install:
- npm install
script:
- npm run build
- npm test
deploy:
  provider: heroku
  api_key:
    secure: hvFo1ovQYLNkDP1emX2FHI37pk8pVjsgeuMawgi3Ei41DoDP2uuJrskAUKB9Z28ZQH0uFz/AKNqc8wcO/jU5esrLTxR6BSioO/0SoUcV4uPMGwssw4xD/PfX3u1ktuwMoG/Rk8nSNUnZefV/sRQ2F1xBSeeUKXsE4IQYzQTAXkayElNhAbzwZzWSNZzZbS7ng1PKiWYajR3pAroJILUFUWgHqjIAhDONK54zxGbogFwbnudRVOQ+FG1KYFbfo7VJ1mbBslMAjtizIlL53FHOvCNDG9OlDZ5DAolP/D5ObHwM6wxBQOfT99iw5pVi1lgn7VTYtaBu8z0RRtafW/KX2mR/e1Q+uAKEBrQ7q8BRKeMZCpLqswmlpN1IIQhXgSw+2JTNHY5yKfjnhX9Frbx4M1NX0xwrxOr2fbzkLVGTIQQ3kNjS7ln4e3x9eQo/U1LMT0GZ1f0US9iV/hyGizB2h2CSOE0VdZugAGG+HGpBFi6mo/81kDqr7E7Ui/GF/RQGMfwc4MGckIM1f4jNUK8748Zmwo0trNnER1cfDFzveX/vWAd5VsZusvp2Mw0X0gajPtIsdlqzs6c4Gaxg38xQpOBtNqtr9wnO/5KjucU5YqX0nKBsblUgPNMxxOZqv9nXxHqqv8IBZoYQkp0qSR1zwVRJR6pcIW61SBr7c3Wywe4=
  app: coding-domain
  skip_cleanup: true
  on:
    repo: SlimeDevs/chat-app
env:
  global:
  - PORT_TEST=3000
