sudo: false
language: node_js
node_js:
- lts/*
cache:
- node_modules
install:
- npm install
script:
- npm run build
- npm test
deploy:
  provider: heroku
  api_key:
    secure: EbLc1e9rlQ4fBS0UaLY63mhVLSYsX25mpymXuqVtFsEKbt0fk9hnuvdemfltpr3EGniBbgsuhI8qOoPSx7Z8ziIPiROChNu1VVZrK+8DEWSRG/fRFJajef/5dtXueDCA3N7ThumC2i8TH/zrT5Bo9agC1hcCzrLRZE38UNpNuwhRrK6Fw8t9JvYpsrGU9I/Z3uWfimq9OoHvZlRaYbhOHK+0jdFcCGPeBbV0f8mkembp1WgATLsBfdgu6W/Q7NjEZbWFzET+kESVd0jhswyRHj4LWlos9Fyn7ts/z6fA0fuGBuOe/XBx4FZ6cxyBOD4OuVlhY+x1z+FKuVgp+BosUkpZ3d1Q2UYrpItl2HAiLBbypH/Y7onwgfSexwCA3obgkJIN8RBU3YS4yaQpFVbmy3b1NMrNGpHm8LMkp4YHEIOZKG3b7DeggsqHcopQ7sJkCRMWg+OJm5LIIEJrJyPq/ySbiLIqrQx1nc0sTNp6PMwK4C8zGf//uCWk61wIcHQthMJD7NmPGvz6H0dYlyXhgZhNvTirW+ze0F78dgj9OzVwJRcL6cFg/uEI6Yjgy6ErHoT/tKZio2/A18P+W2GbZ4qJrF5f9gXQDyL+ENTDOCfWwurcJos77qvN+QfqEwfWUpRunNC2eHEnMgCZU0di5l3IovSIuAOPfDsVSUPRLDE=
  app: coding-domain-chat
  skip_cleanup: true
  on:
    repo: SlimeDevs/chat-app
env:
  global:
  - PORT_TEST=3000
